In [ ]:
import polars as pl

# actually generated by running the following code first
# pl.Config.set_tbl_rows(8)
penguins = pl.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

shape: (344, 7)
┌─────────┬───────────┬────────────────┬───────────────┬───────────────────┬─────────────┬────────┐
│ species ┆ island    ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex    │
│ ---     ┆ ---       ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---    │
│ str     ┆ str       ┆ f64            ┆ f64           ┆ i64               ┆ i64         ┆ str    │
╞═════════╪═══════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪════════╡
│ Adelie  ┆ Torgersen ┆ 39.1           ┆ 18.7          ┆ 181               ┆ 3750        ┆ MALE   │
│ Adelie  ┆ Torgersen ┆ 39.5           ┆ 17.4          ┆ 186               ┆ 3800        ┆ FEMALE │
│ Adelie  ┆ Torgersen ┆ 40.3           ┆ 18.0          ┆ 195               ┆ 3250        ┆ FEMALE │
│ Adelie  ┆ Torgersen ┆ null           ┆ null          ┆ null              ┆ null        ┆ null   │
│ …       ┆ …         ┆ …              ┆ …             ┆ …                 ┆ …           ┆ …      │
│ Gentoo  ┆ Biscoe    ┆ 46.8           ┆ 14.3          ┆ 215               ┆ 4850        ┆ FEMALE │
│ Gentoo  ┆ Biscoe    ┆ 50.4           ┆ 15.7          ┆ 222               ┆ 5750        ┆ MALE   │
│ Gentoo  ┆ Biscoe    ┆ 45.2           ┆ 14.8          ┆ 212               ┆ 5200        ┆ FEMALE │
│ Gentoo  ┆ Biscoe    ┆ 49.9           ┆ 16.1          ┆ 213               ┆ 5400        ┆ MALE   │
└─────────┴───────────┴────────────────┴───────────────┴───────────────────┴─────────────┴────────┘

In [ ]:
import polars as pl

# actually generated by running the following code first
# pl.Config.set_fmt_str_lengths(5)
penguins = pl.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

shape: (344, 7)
┌────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ speci… ┆ islan… ┆ bill_… ┆ bill_… ┆ flipp… ┆ body_… ┆ sex    │
│ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ str    ┆ str    ┆ f64    ┆ f64    ┆ i64    ┆ i64    ┆ str    │
╞════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ Adeli… ┆ Torge… ┆ 39.1   ┆ 18.7   ┆ 181    ┆ 3750   ┆ MALE   │
│ Adeli… ┆ Torge… ┆ 39.5   ┆ 17.4   ┆ 186    ┆ 3800   ┆ FEMAL… │
│ Adeli… ┆ Torge… ┆ 40.3   ┆ 18.0   ┆ 195    ┆ 3250   ┆ FEMAL… │
│ Adeli… ┆ Torge… ┆ null   ┆ null   ┆ null   ┆ null   ┆ null   │
│ Adeli… ┆ Torge… ┆ 36.7   ┆ 19.3   ┆ 193    ┆ 3450   ┆ FEMAL… │
│ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ Gento… ┆ Bisco… ┆ null   ┆ null   ┆ null   ┆ null   ┆ null   │
│ Gento… ┆ Bisco… ┆ 46.8   ┆ 14.3   ┆ 215    ┆ 4850   ┆ FEMAL… │
│ Gento… ┆ Bisco… ┆ 50.4   ┆ 15.7   ┆ 222    ┆ 5750   ┆ MALE   │
│ Gento… ┆ Bisco… ┆ 45.2   ┆ 14.8   ┆ 212    ┆ 5200   ┆ FEMAL… │
│ Gento… ┆ Bisco… ┆ 49.9   ┆ 16.1   ┆ 213    ┆ 5400   ┆ MALE   │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┘

In [ ]:
import polars as pl

# actually generated by running the following code first
# pl.Config.set_tbl_rows(8)
# pl.Config.set_fmt_str_lengths(5)
penguins = pl.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

shape: (344, 7)
┌────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ speci… ┆ islan… ┆ bill_… ┆ bill_… ┆ flipp… ┆ body_… ┆ sex    │
│ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ str    ┆ str    ┆ f64    ┆ f64    ┆ i64    ┆ i64    ┆ str    │
╞════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ Adeli… ┆ Torge… ┆ 39.1   ┆ 18.7   ┆ 181    ┆ 3750   ┆ MALE   │
│ Adeli… ┆ Torge… ┆ 39.5   ┆ 17.4   ┆ 186    ┆ 3800   ┆ FEMAL… │
│ Adeli… ┆ Torge… ┆ 40.3   ┆ 18.0   ┆ 195    ┆ 3250   ┆ FEMAL… │
│ Adeli… ┆ Torge… ┆ null   ┆ null   ┆ null   ┆ null   ┆ null   │
│ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ Gento… ┆ Bisco… ┆ 46.8   ┆ 14.3   ┆ 215    ┆ 4850   ┆ FEMAL… │
│ Gento… ┆ Bisco… ┆ 50.4   ┆ 15.7   ┆ 222    ┆ 5750   ┆ MALE   │
│ Gento… ┆ Bisco… ┆ 45.2   ┆ 14.8   ┆ 212    ┆ 5200   ┆ FEMAL… │
│ Gento… ┆ Bisco… ┆ 49.9   ┆ 16.1   ┆ 213    ┆ 5400   ┆ MALE   │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┘

In [1]:
# this is usually a non-deterministic computation
# running it multiple times will yield different results
import polars as pl

penguins = pl.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins["island"].value_counts()

shape: (3, 2)
┌───────────┬───────┐
│ island    ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ Dream     ┆ 124   │
│ Biscoe    ┆ 168   │
│ Torgersen ┆ 52    │
└───────────┴───────┘