In [76]:
import html_test

In [77]:
import pandas as pd

penguins = pd.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [78]:
import pandas as pd

iguanas = pd.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
iguanas

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [79]:
iguanas.eq(penguins)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True
3,True,True,False,False,False,False,False
4,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...
339,True,True,False,False,False,False,False
340,True,True,True,True,True,True,True
341,True,True,True,True,True,True,True
342,True,True,True,True,True,True,True
343,True,True,True,True,True,True,True

In [80]:
penguins.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

In [81]:
import importlib
importlib.reload(html_test)

df = html_test.get_dataframe("dataframe-test.ipynb", 2)
df = df[df.iloc[:, 0].astype(str) != "..."].reset_index(drop=True)
df

,Unnamed: 0,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
6,340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
7,341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
8,342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
9,343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [82]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         10 non-null     str
 1   species            10 non-null     str
 2   island             10 non-null     str
 3   bill_length_mm     8 non-null      str
 4   bill_depth_mm      8 non-null      str
 5   flipper_length_mm  8 non-null      str
 6   body_mass_g        8 non-null      str
 7   sex                8 non-null      str
dtypes: str(8)
memory usage: 772.0 bytes

In [83]:
from pandas.api.types import infer_dtype

dtype_summary = (
df.apply(lambda s: infer_dtype(s, skipna=True))
.rename("pd_infer_dtype_skipna")
.reset_index()
.rename(columns={"index": "column"})
)

In [84]:
dtype_summary.sort_values("pd_infer_dtype_skipna")

              column pd_infer_dtype_skipna
0         Unnamed: 0                string
1            species                string
2             island                string
3     bill_length_mm                string
4      bill_depth_mm                string
5  flipper_length_mm                string
6        body_mass_g                string
7                sex                string

In [85]:
dfn = df.convert_dtypes()
dfn

,Unnamed: 0,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,3,Adelie,Torgersen,<NA>,<NA>,<NA>,<NA>,<NA>
4,4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,339,Gentoo,Biscoe,<NA>,<NA>,<NA>,<NA>,<NA>
6,340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
7,341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
8,342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
9,343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [86]:
dfn.dtypes

Unnamed: 0           string
species              string
island               string
bill_length_mm       string
bill_depth_mm        string
flipper_length_mm    string
body_mass_g          string
sex                  string
dtype: object

In [87]:
dfn.eq(penguins)

,Unnamed: 0,bill_depth_mm,bill_length_mm,body_mass_g,flipper_length_mm,island,sex,species
0,<NA>,False,False,False,False,True,True,True
1,<NA>,False,False,False,False,True,True,True
2,<NA>,False,False,False,False,True,True,True
3,<NA>,<NA>,<NA>,<NA>,<NA>,True,<NA>,True
4,<NA>,False,False,False,False,True,True,True
...,...,...,...,...,...,...,...,...
339,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
340,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
341,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
342,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
343,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [88]:
import pandas as pd

# pd.set_option("display.min_rows", 8)
penguins = pd.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [89]:
import importlib
importlib.reload(html_test)

df = html_test.get_dataframe("dataframe-test.ipynb", 4)
df = df[df.iloc[:, 0].astype(str) != "..."].reset_index(drop=True)
df

,Unnamed: 0,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,0,True,True,True,True,True,True,True
1,1,True,True,True,True,True,True,True
2,2,True,True,True,True,True,True,True
3,3,True,True,False,False,False,False,False
4,4,True,True,True,True,True,True,True
5,339,True,True,False,False,False,False,False
6,340,True,True,True,True,True,True,True
7,341,True,True,True,True,True,True,True
8,342,True,True,True,True,True,True,True
9,343,True,True,True,True,True,True,True

In [90]:
df

,Unnamed: 0,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,0,True,True,True,True,True,True,True
1,1,True,True,True,True,True,True,True
2,2,True,True,True,True,True,True,True
3,3,True,True,False,False,False,False,False
4,4,True,True,True,True,True,True,True
5,339,True,True,False,False,False,False,False
6,340,True,True,True,True,True,True,True
7,341,True,True,True,True,True,True,True
8,342,True,True,True,True,True,True,True
9,343,True,True,True,True,True,True,True

In [91]:
import pandas as pd

# pd.set_option("display.min_rows", 8)
# pd.set_option("display.max_colwidth", 6)
# pd.set_option("display.min_rows", 8)
penguins = pd.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [92]:
import importlib
importlib.reload(html_test)

df = html_test.get_dataframe("dataframe-test.ipynb", 6)
if df is None:
    df = penguins.copy()

df = df.set_index("species")
df.groupby(level="species").mean(numeric_only=True)

,Unnamed: 0.1,Unnamed: 0,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g
species,,,,,,
Adelie,2.0,2.0,38.900,18.350,188.75,3562.5
Gentoo,7.0,341.0,48.075,15.225,215.50,5300.0

In [93]:
import pandas as pd

penguins = pd.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [94]:
import importlib
from io import StringIO

importlib.reload(html_test)

df_fixed, cleaned_html = html_test.parse_dataframe_with_bs4(
    "dataframe-test.ipynb",
    2,
    skiprows=[0],
    drop_ellipsis_rows=True,
    return_html=True,
)

df_from_clean_html = pd.read_html(StringIO(cleaned_html), skiprows=[0])[0]
df_from_clean_html.head()

     0  Adelie  Torgersen  39.1  18.7  181.0  3750.0    MALE
0    1  Adelie  Torgersen  39.5  17.4  186.0  3800.0  FEMALE
1    2  Adelie  Torgersen  40.3  18.0  195.0  3250.0  FEMALE
2    3  Adelie  Torgersen   NaN   NaN    NaN     NaN     NaN
3    4  Adelie  Torgersen  36.7  19.3  193.0  3450.0  FEMALE
4  339  Gentoo     Biscoe   NaN   NaN    NaN     NaN     NaN

In [95]:
df.info()

<class 'pandas.DataFrame'>
Index: 10 entries, Adelie to Gentoo
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       10 non-null     int64
 1   Unnamed: 0         10 non-null     int64
 2   island             10 non-null     str
 3   bill_length_mm     8 non-null      float64
 4   bill_depth_mm      8 non-null      float64
 5   flipper_length_mm  8 non-null      float64
 6   body_mass_g        8 non-null      float64
 7   sex                8 non-null      str
dtypes: float64(4), int64(2), str(2)
memory usage: 720.0+ bytes

In [96]:
df2 = df.infer_objects()
df2.info()

<class 'pandas.DataFrame'>
Index: 10 entries, Adelie to Gentoo
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       10 non-null     int64
 1   Unnamed: 0         10 non-null     int64
 2   island             10 non-null     str
 3   bill_length_mm     8 non-null      float64
 4   bill_depth_mm      8 non-null      float64
 5   flipper_length_mm  8 non-null      float64
 6   body_mass_g        8 non-null      float64
 7   sex                8 non-null      str
dtypes: float64(4), int64(2), str(2)
memory usage: 720.0+ bytes

In [97]:
df.loc[3, "bill_length_mm"]

KeyError: 3