In [ ]:
import numpy as np

# actually generated by running the following code first
# np.set_printoptions(precision=5)
np.arange(25).reshape(5, 5) * np.pi

array([[ 0.     ,  3.14159,  6.28319,  9.42478, 12.56637],
       [15.70796, 18.84956, 21.99115, 25.13274, 28.27433],
       [31.41593, 34.55752, 37.69911, 40.8407 , 43.9823 ],
       [47.12389, 50.26548, 53.40708, 56.54867, 59.69026],
       [62.83185, 65.97345, 69.11504, 72.25663, 75.39822]])

In [ ]:
import numpy as np

# actually generated by running the following code first
# np.set_printoptions(threshold=4, edgeitems=2)
np.arange(25).reshape(5, 5) * np.pi

array([[ 0.        ,  3.14159265, ...,  9.42477796, 12.56637061],
       [15.70796327, 18.84955592, ..., 25.13274123, 28.27433388],
       ...,
       [47.1238898 , 50.26548246, ..., 56.54866776, 59.69026042],
       [62.83185307, 65.97344573, ..., 72.25663103, 75.39822369]],
      shape=(5, 5))

In [ ]:
import numpy as np

# actually generated by running the following code first
# np.set_printoptions(precision=5, threshold=4, edgeitems=2)
np.arange(25).reshape(5, 5) * np.pi

array([[ 0.     ,  3.14159, ...,  9.42478, 12.56637],
       [15.70796, 18.84956, ..., 25.13274, 28.27433],
       ...,
       [47.12389, 50.26548, ..., 56.54867, 59.69026],
       [62.83185, 65.97345, ..., 72.25663, 75.39822]], shape=(5, 5))

In [ ]:
import polars as pl

# actually generated by running the following code first
# pl.Config.set_tbl_rows(8)
penguins = pl.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

shape: (344, 7)
┌─────────┬───────────┬────────────────┬───────────────┬───────────────────┬─────────────┬────────┐
│ species ┆ island    ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex    │
│ ---     ┆ ---       ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---    │
│ str     ┆ str       ┆ f64            ┆ f64           ┆ i64               ┆ i64         ┆ str    │
╞═════════╪═══════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪════════╡
│ Adelie  ┆ Torgersen ┆ 39.1           ┆ 18.7          ┆ 181               ┆ 3750        ┆ MALE   │
│ Adelie  ┆ Torgersen ┆ 39.5           ┆ 17.4          ┆ 186               ┆ 3800        ┆ FEMALE │
│ Adelie  ┆ Torgersen ┆ 40.3           ┆ 18.0          ┆ 195               ┆ 3250        ┆ FEMALE │
│ Adelie  ┆ Torgersen ┆ null           ┆ null          ┆ null              ┆ null        ┆ null   │
│ …       ┆ …         ┆ …              ┆ …             ┆ …                 ┆ …           ┆ …      │
│ Gentoo  ┆ Biscoe    ┆ 46.8           ┆ 14.3          ┆ 215               ┆ 4850        ┆ FEMALE │
│ Gentoo  ┆ Biscoe    ┆ 50.4           ┆ 15.7          ┆ 222               ┆ 5750        ┆ MALE   │
│ Gentoo  ┆ Biscoe    ┆ 45.2           ┆ 14.8          ┆ 212               ┆ 5200        ┆ FEMALE │
│ Gentoo  ┆ Biscoe    ┆ 49.9           ┆ 16.1          ┆ 213               ┆ 5400        ┆ MALE   │
└─────────┴───────────┴────────────────┴───────────────┴───────────────────┴─────────────┴────────┘

In [ ]:
import polars as pl

# actually generated by running the following code first
# pl.Config.set_fmt_str_lengths(5)
penguins = pl.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

shape: (344, 7)
┌────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ speci… ┆ islan… ┆ bill_… ┆ bill_… ┆ flipp… ┆ body_… ┆ sex    │
│ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ str    ┆ str    ┆ f64    ┆ f64    ┆ i64    ┆ i64    ┆ str    │
╞════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ Adeli… ┆ Torge… ┆ 39.1   ┆ 18.7   ┆ 181    ┆ 3750   ┆ MALE   │
│ Adeli… ┆ Torge… ┆ 39.5   ┆ 17.4   ┆ 186    ┆ 3800   ┆ FEMAL… │
│ Adeli… ┆ Torge… ┆ 40.3   ┆ 18.0   ┆ 195    ┆ 3250   ┆ FEMAL… │
│ Adeli… ┆ Torge… ┆ null   ┆ null   ┆ null   ┆ null   ┆ null   │
│ Adeli… ┆ Torge… ┆ 36.7   ┆ 19.3   ┆ 193    ┆ 3450   ┆ FEMAL… │
│ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ Gento… ┆ Bisco… ┆ null   ┆ null   ┆ null   ┆ null   ┆ null   │
│ Gento… ┆ Bisco… ┆ 46.8   ┆ 14.3   ┆ 215    ┆ 4850   ┆ FEMAL… │
│ Gento… ┆ Bisco… ┆ 50.4   ┆ 15.7   ┆ 222    ┆ 5750   ┆ MALE   │
│ Gento… ┆ Bisco… ┆ 45.2   ┆ 14.8   ┆ 212    ┆ 5200   ┆ FEMAL… │
│ Gento… ┆ Bisco… ┆ 49.9   ┆ 16.1   ┆ 213    ┆ 5400   ┆ MALE   │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┘

In [ ]:
import polars as pl

# actually generated by running the following code first
# pl.Config.set_tbl_rows(8)
# pl.Config.set_fmt_str_lengths(5)
penguins = pl.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

shape: (344, 7)
┌────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ speci… ┆ islan… ┆ bill_… ┆ bill_… ┆ flipp… ┆ body_… ┆ sex    │
│ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ str    ┆ str    ┆ f64    ┆ f64    ┆ i64    ┆ i64    ┆ str    │
╞════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ Adeli… ┆ Torge… ┆ 39.1   ┆ 18.7   ┆ 181    ┆ 3750   ┆ MALE   │
│ Adeli… ┆ Torge… ┆ 39.5   ┆ 17.4   ┆ 186    ┆ 3800   ┆ FEMAL… │
│ Adeli… ┆ Torge… ┆ 40.3   ┆ 18.0   ┆ 195    ┆ 3250   ┆ FEMAL… │
│ Adeli… ┆ Torge… ┆ null   ┆ null   ┆ null   ┆ null   ┆ null   │
│ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ Gento… ┆ Bisco… ┆ 46.8   ┆ 14.3   ┆ 215    ┆ 4850   ┆ FEMAL… │
│ Gento… ┆ Bisco… ┆ 50.4   ┆ 15.7   ┆ 222    ┆ 5750   ┆ MALE   │
│ Gento… ┆ Bisco… ┆ 45.2   ┆ 14.8   ┆ 212    ┆ 5200   ┆ FEMAL… │
│ Gento… ┆ Bisco… ┆ 49.9   ┆ 16.1   ┆ 213    ┆ 5400   ┆ MALE   │
└────────┴────────┴────────┴────────┴────────┴────────┴────────┘

In [1]:
# this is usually a non-deterministic computation
# running it multiple times will yield different results
import polars as pl

penguins = pl.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins["island"].value_counts()

shape: (3, 2)
┌───────────┬───────┐
│ island    ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ Dream     ┆ 124   │
│ Biscoe    ┆ 168   │
│ Torgersen ┆ 52    │
└───────────┴───────┘

In [ ]:
import pandas as pd

penguins = pd.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
import pandas as pd

# actually generated by running the following code first
# pd.set_option("display.min_rows", 8)
penguins = pd.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
import pandas as pd

# actually generated by running the following code first
# pd.set_option("display.max_colwidth", 6)
penguins = pd.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Ad...,To...,39.1,18.7,181.0,37...,MALE
1,Ad...,To...,39.5,17.4,186.0,38...,FE...
2,Ad...,To...,40.3,18.0,195.0,32...,FE...
3,Ad...,To...,NaN,NaN,NaN,NaN,NaN
4,Ad...,To...,36.7,19.3,193.0,34...,FE...
...,...,...,...,...,...,...,...
339,Ge...,Bi...,NaN,NaN,NaN,NaN,NaN
340,Ge...,Bi...,46.8,14.3,215.0,48...,FE...
341,Ge...,Bi...,50.4,15.7,222.0,57...,MALE
342,Ge...,Bi...,45.2,14.8,212.0,52...,FE...
343,Ge...,Bi...,49.9,16.1,213.0,54...,MALE

In [ ]:
import pandas as pd

# actually generated by running the following code first
# pd.set_option("display.min_rows", 8)
# pd.set_option("display.max_colwidth", 6)
penguins = pd.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Ad...,To...,39.1,18.7,181.0,37...,MALE
1,Ad...,To...,39.5,17.4,186.0,38...,FE...
2,Ad...,To...,40.3,18.0,195.0,32...,FE...
3,Ad...,To...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
340,Ge...,Bi...,46.8,14.3,215.0,48...,FE...
341,Ge...,Bi...,50.4,15.7,222.0,57...,MALE
342,Ge...,Bi...,45.2,14.8,212.0,52...,FE...
343,Ge...,Bi...,49.9,16.1,213.0,54...,MALE